const CRM_SEND_METHOD_TYPE = {
    SMS: 'SMS',
    FRIENDTALK: 'FRIENDTALK',
    ALIMTALK: 'ALIMTALK',
    MYAPP: 'MYAPP',
}

const CRM_FRIENDTALK_MESSAGE_TYPE = {
    TEXT: 'TEXT',
    IMAGE: 'IMAGE',
    WIDE_IMAGE: 'WIDE_IMAGE',
    WIDE_ITEM_LIST: 'WIDE_ITEM_LIST',
    CAROUSEL_FEED: 'CAROUSEL_FEED',
}
